# Generated by Django 4.2.7 on 2023-11-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_draft_background"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="draft",
            name="picture_objects",
        ),
        migrations.RemoveField(
            model_name="draft",
            name="text_objects",
        ),
        migrations.AddField(
            model_name="pictureobject",
            name="draft",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picture_object",
                to="main.draft",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="textobject",
            name="draft",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_object",
                to="main.draft",
            ),
            preserve_default=False,
        ),
    ]
