# Generated by Django 4.2.7 on 2023-11-25 12:44

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_draft_picture_objects_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawnObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="layer", max_length=100)),
                ("x_position", models.IntegerField()),
                ("y_position", models.IntegerField()),
                (
                    "picture",
                    models.ImageField(
                        null=True, upload_to=main.models.get_picture_object_filepath
                    ),
                ),
                (
                    "draft",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drawn_object",
                        to="main.draft",
                    ),
                ),
            ],
        ),
    ]
