# Generated by Django 4.2.7 on 2023-11-30 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_drawnobject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawnobject",
            name="name",
        ),
        migrations.RemoveField(
            model_name="drawnobject",
            name="x_position",
        ),
        migrations.RemoveField(
            model_name="drawnobject",
            name="y_position",
        ),
        migrations.RemoveField(
            model_name="pictureobject",
            name="name",
        ),
        migrations.RemoveField(
            model_name="textobject",
            name="name",
        ),
    ]
