# Generated by Django 4.2.7 on 2024-01-02 16:11

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_drawnobject_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pictureobject",
            name="height",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pictureobject",
            name="rotate",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pictureobject",
            name="width",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="drawnobject",
            name="picture",
            field=models.ImageField(
                null=True, upload_to=main.models.get_drawn_object_filepath
            ),
        ),
    ]
