# Generated by Django 4.2.7 on 2024-01-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_textobject_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="textobject",
            name="height",
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name="textobject",
            name="width",
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name="textobject",
            name="x_position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="textobject",
            name="y_position",
            field=models.IntegerField(default=0),
        ),
    ]
